### ISSUE TITLE
1.20.5/6 support

### ISSUE THREAD

**Issue by Thanos1716** [Viola-Siemens/Villager-Armor-Layer-Fabric#3]
Upon trying to use this mod with 1.20.6, the game crashes with the following crash log:

<details>
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-05-26 12:27:33
Description: Rendering entity in world

java.lang.NoClassDefFoundError: net/minecraft/class_4057
	at com.hexagram2021.villagerarmor.client.HumanoidArmorLayer.renderArmorPiece(HumanoidArmorLayer.java:59)
	at com.hexagram2021.villagerarmor.client.HumanoidArmorLayer.render(HumanoidArmorLayer.java:45)
	at com.hexagram2021.villagerarmor.client.HumanoidArmorLayer.method_4199(HumanoidArmorLayer.java:30)
	at net.minecraft.class_922.method_4054(class_922.java:149)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:143)
	at net.minecraft.class_761.method_22977(class_761.java:1346)
	at net.minecraft.class_761.method_22710(class_761.java:1103)
	at net.minecraft.class_757.method_3188(class_757.java:1093)
	at net.minecraft.class_757.method_3192(class_757.java:858)
	at net.minecraft.class_310.method_1523(class_310.java:1320)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_4057
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.hexagram2021.villagerarmor.client.HumanoidArmorLayer.renderArmorPiece(HumanoidArmorLayer.java:59)
	at com.hexagram2021.villagerarmor.client.HumanoidArmorLayer.render(HumanoidArmorLayer.java:45)
	at com.hexagram2021.villagerarmor.client.HumanoidArmorLayer.method_4199(HumanoidArmorLayer.java:30)
	at net.minecraft.class_922.method_4054(class_922.java:149)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:143)
	at net.minecraft.class_761.method_22977(class_761.java:1346)
	at net.minecraft.class_761.method_22710(class_761.java:1103)
	at net.minecraft.class_757.method_3188(class_757.java:1093)

-- Entity being rendered --
Details:
	Entity Type: minecraft:villager (net.minecraft.class_1646)
	Entity ID: 942
	Entity Name: Villager
	Entity's Exact location: 0.50, 55.17, 1.50
	Entity's Block location: World: (0,55,1), Section: (at 0,7,1 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:143)
	at net.minecraft.class_761.method_22977(class_761.java:1346)
	at net.minecraft.class_761.method_22710(class_761.java:1103)
	at net.minecraft.class_757.method_3188(class_757.java:1093)
	at net.minecraft.class_757.method_3192(class_757.java:858)
	at net.minecraft.class_310.method_1523(class_310.java:1320)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_963@1fdcd359
	Location: -9.88,-14.64,-9.85 - World: (-10,-15,-10), Section: (at 6,1,6 in -1,-1,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Rotation: 0.0
	Delta: 0.26001382
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:143)
	at net.minecraft.class_761.method_22977(class_761.java:1346)
	at net.minecraft.class_761.method_22710(class_761.java:1103)
	at net.minecraft.class_757.method_3188(class_757.java:1093)
	at net.minecraft.class_757.method_3192(class_757.java:858)
	at net.minecraft.class_310.method_1523(class_310.java:1320)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Uptime --
Details:
	JVM uptime: 93.126s
	Wall uptime: 87.572s
	High-res time: 86.960s
	Client ticks: 1371 ticks / 68.550s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2548)
	at net.minecraft.class_310.method_54580(class_310.java:983)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 1 total; [class_746['nunya'/46, l='ClientLevel', x=10.38, y=68.16, z=11.35]]
	Chunk stats: 961, 307
	Level dimension: minecraft:overworld
	Level spawn location: World: (-208,71,176), Section: (at 0,7,0 in -13,4,11; chunk contains blocks -208,-64,176 to -193,319,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 987 game time, 987 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 163

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader

-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Linux (amd64) version 6.8.9-arch1-2
	Java Version: 21.0.3, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 470267344 bytes (448 MiB) / 1375731712 bytes (1312 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 2
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: TigerLake-LP GT2 [Iris Xe Graphics]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 28350.55
	Virtual memory used (MB): 12135.61
	Swap memory total (MB): 20480.00
	Swap memory used (MB): 593.18
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		fabric-api: Fabric API 0.99.0+1.20.6
			fabric-api-base: Fabric API Base 0.4.40+80f8cf51b0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.59+e9d2a72bb0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.25+be5d88beb0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.20+6dfe4c9bb0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.8+80f8cf51b0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.50+80f8cf51b0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.12+7f945d5bb0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.45+f71b366fb0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.24+80f8cf51b0
			fabric-commands-v0: Fabric Commands (v0) 0.2.62+df3654b3b0
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.5+b82b2392b0
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.4+7f945d5bb0
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.1.0+70fd1b46b0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.27+80f8cf51b0
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.16+2a2c66b6b0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 19.2.0+a5d5299db0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.68+94793913b0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.8+e9d2a72bb0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.6+c5fc38b3b0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.50+80f8cf51b0
			fabric-item-api-v1: Fabric Item API (v1) 8.2.1+8e8943b6b0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.39+aae0949ab0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.45+80f8cf51b0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.43+df3654b3b0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.4+c5fc38b3b0
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.5+97f703dab0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.11+a7dc0e41b0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.12+80f8cf51b0
			fabric-models-v0: Fabric Models (v0) 0.4.11+9386d8a7b0
			fabric-networking-api-v1: Fabric Networking API (v1) 4.0.8+0dca0349b0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.4+c5fc38b3b0
			fabric-particles-v1: Fabric Particles (v1) 4.0.0+c5fc38b3b0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.3+c5fc38b3b0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.16+ad474493b0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.12+97f703dab0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.12+80f8cf51b0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.61+df3654b3b0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.46+73761d2eb0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.3+2c869dedb0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.64+df3654b3b0
			fabric-rendering-v1: Fabric Rendering (v1) 4.2.4+b21c00cbb0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.0+a5d5299db0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.0+c0e5481fb0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.21+7b70ea8ab0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.73+8c7b71c2b0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.21+c5fc38b3b0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.6+c5fc38b3b0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.10+74e2f560b0
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.20.6
		villagerarmor: Villager Armor Layer 5.2.0
	Launched Version: 1.20.6
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Mesa Intel(R) Xe Graphics (TGL GT2) GL version 4.6 (Core Profile) Mesa 24.0.7-arch1.3, Intel
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader
	Current Language: en_us
	Locale: en_US
	CPU: 8x 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['nunya'/46, l='ServerLevel[New World]', x=10.38, y=68.16, z=11.35]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, trade_rebalance, update_1_21, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 8089120252935651349

</details>

**Comment by Viola-Siemens** [comment]
Thanks for supporting, coming soon.
